name: marketforge
version: 1.0.0
config-version: 2
profile: marketforge

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]

on-run-start:
  - "{{ create_raw_views() }}"

models:
  marketforge:
    staging:
      +materialized: view
      +schema: staging
