name: marketforge
version: 1.0.0
config-version: 2
profile: marketforge

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]

on-run-start:
  - "{{ create_raw_views() }}"
  - "{{ create_operational_views() }}"

models:
  marketforge:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts

seeds:
  marketforge:
    +schema: reference
