import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { Activity, Boxes, ChartNoAxesCombined, CircleGauge, Database, GitBranch, HardDrive, ListChecks, Play, ServerCog, ShieldCheck } from "lucide-react";
import { api, Dataset, Lineage, PricePoint, Readiness, Security } from "./api";
import "./styles.css";

type View = "Overview" | "Datasets" | "Lineage" | "Pipeline Runs" | "Data Quality" | "Analytics" | "System";
const navigation: [View, React.ComponentType<{ size?: number }>][] = [
  ["Overview", CircleGauge], ["Datasets", Database], ["Lineage", GitBranch],
  ["Pipeline Runs", Play], ["Data Quality", ListChecks],
  ["Analytics", ChartNoAxesCombined], ["System", ServerCog],
];

const number = (value: number) => new Intl.NumberFormat("en-US", { notation: value > 999999 ? "compact" : "standard" }).format(value);
const age = (value?: string | null) => {
  if (!value) return "No evidence";
  const hours = Math.max(0, (Date.now() - new Date(value).getTime()) / 36e5);
  return hours < 24 ? `${Math.round(hours)}h ago` : `${Math.round(hours / 24)}d ago`;
};
function Status({ value }: { value: string }) { return <span className={`status ${value.toLowerCase()}`}><i />{value.replace("_", " ")}</span>; }
function Empty({ title, detail }: { title: string; detail: string }) { return <div className="empty"><Boxes size={28}/><h3>{title}</h3><p>{detail}</p></div>; }
function ErrorBanner({ message }: { message: string }) { return <div className="error"><Activity size={18}/><div><strong>Published analytics unavailable</strong><span>{message}</span></div></div>; }
function Metric({ label, value, note }: { label: string; value: string | number; note: string }) { return <article className="metric"><span>{label}</span><strong>{value}</strong><small>{note}</small></article>; }

function Overview({ datasets, error }: { datasets: Dataset[]; error?: string }) {
  const healthy = datasets.filter(d => d.status.toLowerCase() === "healthy").length;
  const quarantined = datasets.reduce((sum, d) => sum + (d.quarantine_count ?? 0), 0);
  const failed = datasets.filter(d => !["healthy", "unknown"].includes(d.status.toLowerCase())).length;
  const latest = datasets.map(d => d.last_successful_run_at).filter(Boolean).sort().at(-1);
  return <><header className="page-head"><div><span className="eyebrow">CONTROL PLANE / OVERVIEW</span><h1>Platform overview</h1><p>Operational state across published analytical datasets.</p></div><Status value={error ? "not_ready" : "ready"}/></header>
    {error && <ErrorBanner message={error}/>}<section className="metrics">
      <Metric label="Datasets healthy" value={`${healthy} / ${datasets.length || "—"}`} note="Published data products"/>
      <Metric label="Latest successful run" value={latest ? age(latest) : "—"} note="Across all datasets"/>
      <Metric label="Failed checks" value={failed} note="Current quality state"/>
      <Metric label="Quarantined records" value={number(quarantined)} note="Latest successful runs"/>
    </section><section className="panel"><div className="panel-title"><div><h2>Dataset health</h2><p>Freshness is data state, independent of API readiness.</p></div></div>
      {datasets.length ? <DatasetTable rows={datasets}/> : <Empty title="No published health mart" detail="Run the dbt publication pipeline to populate this view."/>}</section></>;
}
function DatasetTable({ rows }: { rows: Dataset[] }) { return <div className="table-wrap"><table><thead><tr><th>Dataset</th><th>Status</th><th>Freshness</th><th>Rows</th><th>Last run</th></tr></thead><tbody>{rows.map(row => <tr key={row.dataset}><td><b>{row.dataset}</b></td><td><Status value={row.status}/></td><td>{age(row.latest_event_time)}</td><td className="mono">{number(row.row_count)}</td><td className="mono muted">{row.last_successful_run?.slice(0, 12) ?? "—"}</td></tr>)}</tbody></table></div>; }
function Datasets({ rows }: { rows: Dataset[] }) { return <><header className="page-head"><div><span className="eyebrow">CATALOG</span><h1>Datasets</h1><p>Published data products and their operational contracts.</p></div></header><section className="dataset-grid">{rows.map(d => <article className="dataset-card" key={d.dataset}><div><Database size={18}/><Status value={d.status}/></div><h2>{d.dataset}</h2><p>Source-normalized analytical dataset.</p><dl><div><dt>Rows</dt><dd>{number(d.row_count)}</dd></div><div><dt>Latest event</dt><dd>{age(d.latest_event_time)}</dd></div><div><dt>Duplicates</dt><dd>{d.duplicate_count ?? 0}</dd></div><div><dt>Quarantine</dt><dd>{d.quarantine_count ?? 0}</dd></div></dl></article>)}</section>{!rows.length && <Empty title="Dataset catalog is empty" detail="Published marts will appear here after a successful materialization."/>}</> }
function LineageView({ datasets }: { datasets: Dataset[] }) { const [selected,setSelected]=useState(datasets[0]?.dataset ?? "prices"); const [graph,setGraph]=useState<Lineage>(); const [error,setError]=useState(""); useEffect(()=>{setError("");api.lineage(selected).then(setGraph).catch(e=>setError(e.message));},[selected]); const ordered=graph?[...graph.nodes].sort((a,b)=>{const rank=(id:string)=>{const seen=new Set<string>();const visit=(value:string):number=>{if(seen.has(value))return 0;seen.add(value);const parents=graph.edges.filter(e=>e.to===value);return parents.length?1+Math.max(...parents.map(e=>visit(e.from))):0};return visit(id)};return rank(a.id)-rank(b.id)}):[]; return <><header className="page-head"><div><span className="eyebrow">DEPENDENCY GRAPH</span><h1>Lineage</h1><p>From external source and immutable Parquet to analytical consumer.</p></div><select value={selected} onChange={e=>setSelected(e.target.value)}>{(datasets.length?datasets:[{dataset:"prices"} as Dataset]).map(d=><option key={d.dataset}>{d.dataset}</option>)}</select></header>{error&&!graph?<ErrorBanner message={error}/>:<section className="lineage panel">{ordered.map((node,index)=><React.Fragment key={node.id}><article><small>{node.type}</small><b>{node.name}</b></article>{index<ordered.length-1&&<span>→</span>}</React.Fragment>)}</section>}</>; }
function Runs() { return <><header className="page-head"><div><span className="eyebrow">EXECUTION HISTORY</span><h1>Pipeline runs</h1><p>Ingestion, transformation, and publication activity.</p></div></header><Empty title="Run history endpoint not published" detail="Operational run metadata exists locally and will be exposed through a bounded API before this table is enabled."/></>; }
function Quality({ rows }: { rows: Dataset[] }) { return <><header className="page-head"><div><span className="eyebrow">TRUST & QUALITY</span><h1>Data quality</h1><p>Nulls, duplicates, quarantine, and freshness signals.</p></div></header>{rows.length?<section className="quality-grid">{rows.map(d=><article className="panel" key={d.dataset}><div className="quality-head"><b>{d.dataset}</b><Status value={d.status}/></div><div className="bar-label"><span>Completeness</span><b>{((1-(d.null_rate??0))*100).toFixed(1)}%</b></div><div className="bar"><i style={{width:`${(1-(d.null_rate??0))*100}%`}}/></div><p>{d.duplicate_count??0} duplicates · {d.quarantine_count??0} quarantined</p></article>)}</section>:<Empty title="No quality observations" detail="Quality results appear after the health mart is published."/>}</>; }
function Analytics() { const [items,setItems]=useState<Security[]>([]); const [selected,setSelected]=useState(""); const [history,setHistory]=useState<PricePoint[]>([]); const [error,setError]=useState(""); useEffect(()=>{api.securities().then(r=>{setItems(r.data);setSelected(r.data[0]?.symbol??"")}).catch(e=>setError(e.message))},[]); useEffect(()=>{if(selected)api.history(selected).then(r=>setHistory(r.data.slice().reverse())).catch(e=>setError(e.message))},[selected]); const prices=history.map(p=>p.close); const min=Math.min(...prices),max=Math.max(...prices); const points=history.map((p,i)=>`${(i/Math.max(1,history.length-1))*760},${160-((p.close-min)/Math.max(1,max-min))*130}`).join(" "); return <><header className="page-head"><div><span className="eyebrow">ANALYTICAL CONSUMER</span><h1>Security analytics</h1><p>Proof that governed marts support downstream analysis.</p></div>{items.length>0&&<select value={selected} onChange={e=>setSelected(e.target.value)}>{items.map(s=><option key={`${s.symbol}-${s.source}`}>{s.symbol}</option>)}</select>}</header>{error?<ErrorBanner message={error}/>:history.length?<section className="panel chart"><div><h2>{selected} price history</h2><span>{history.length} observations</span></div><svg viewBox="0 0 760 180" role="img" aria-label={`${selected} closing-price history`}><line x1="0" y1="160" x2="760" y2="160"/><polyline points={points}/></svg></section>:<Empty title="No analytical series" detail="Publish mart_security_daily to enable governed market analytics."/>}</>; }
function System({ ready }: { ready?: Readiness }) { return <><header className="page-head"><div><span className="eyebrow">RUNTIME</span><h1>System</h1><p>Serving dependencies and process-local cache telemetry.</p></div><Status value={ready?.status??"unknown"}/></header><section className="system-grid">{ready?.checks.map(c=><article className="panel" key={c.component}><HardDrive size={20}/><h2>{c.component.replace("_"," ")}</h2><Status value={c.status}/><p>{c.detail}</p></article>)}</section>{ready&&<section className="panel cache"><div><h2>Query cache</h2><p>Bounded in-process TTL/LRU cache</p></div><div><Metric label="Hit rate" value={`${((ready.cache.hit_rate??0)*100).toFixed(1)}%`} note="Since process start"/><Metric label="Entries" value={ready.cache.entries??0} note="Maximum 256"/><Metric label="Evictions" value={ready.cache.evictions??0} note="Capacity pressure"/></div></section>}</>; }

function App() { const [view,setView]=useState<View>("Overview"); const [datasets,setDatasets]=useState<Dataset[]>([]); const [ready,setReady]=useState<Readiness>(); const [error,setError]=useState<string>(); useEffect(()=>{api.health().then(r=>setDatasets(r.data)).catch(e=>setError(e.message));api.readiness().then(setReady).catch(async e=>{setError(e.message)});},[]); return <div className="shell"><aside><div className="brand"><div><ShieldCheck size={20}/></div><span>Market<b>Forge</b><small>DATA PLATFORM</small></span></div><nav>{navigation.map(([name,Icon])=><button key={name} className={view===name?"active":""} onClick={()=>setView(name)}><Icon size={17}/>{name}</button>)}</nav><footer><span className="pulse"/>API {ready?.status??"checking"}</footer></aside><main>{view==="Overview"&&<Overview datasets={datasets} error={error}/>} {view==="Datasets"&&<Datasets rows={datasets}/>} {view==="Lineage"&&<LineageView datasets={datasets}/>} {view==="Pipeline Runs"&&<Runs/>} {view==="Data Quality"&&<Quality rows={datasets}/>} {view==="Analytics"&&<Analytics/>} {view==="System"&&<System ready={ready}/>}</main></div> }

createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
